// Generated by gencpp from file beginner_tutorials/add_two_int.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ADD_TWO_INT_H
#define BEGINNER_TUTORIALS_MESSAGE_ADD_TWO_INT_H

#include <ros/service_traits.h>


#include <beginner_tutorials/add_two_intRequest.h>
#include <beginner_tutorials/add_two_intResponse.h>


namespace beginner_tutorials
{

struct add_two_int
{

typedef add_two_intRequest Request;
typedef add_two_intResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add_two_int
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::add_two_int > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::beginner_tutorials::add_two_int&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::add_two_int > {
  static const char* value()
  {
    return "beginner_tutorials/add_two_int";
  }

  static const char* value(const ::beginner_tutorials::add_two_int&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::add_two_intRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::add_two_int >
template<>
struct MD5Sum< ::beginner_tutorials::add_two_intRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::add_two_int >::value();
  }
  static const char* value(const ::beginner_tutorials::add_two_intRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::add_two_intRequest> should match
// service_traits::DataType< ::beginner_tutorials::add_two_int >
template<>
struct DataType< ::beginner_tutorials::add_two_intRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::add_two_int >::value();
  }
  static const char* value(const ::beginner_tutorials::add_two_intRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::add_two_intResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::add_two_int >
template<>
struct MD5Sum< ::beginner_tutorials::add_two_intResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::add_two_int >::value();
  }
  static const char* value(const ::beginner_tutorials::add_two_intResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::add_two_intResponse> should match
// service_traits::DataType< ::beginner_tutorials::add_two_int >
template<>
struct DataType< ::beginner_tutorials::add_two_intResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::add_two_int >::value();
  }
  static const char* value(const ::beginner_tutorials::add_two_intResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ADD_TWO_INT_H
