// Generated by gencpp from file beginner_tutorials/call_map.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_CALL_MAP_H
#define BEGINNER_TUTORIALS_MESSAGE_CALL_MAP_H

#include <ros/service_traits.h>


#include <beginner_tutorials/call_mapRequest.h>
#include <beginner_tutorials/call_mapResponse.h>


namespace beginner_tutorials
{

struct call_map
{

typedef call_mapRequest Request;
typedef call_mapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct call_map
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::call_map > {
  static const char* value()
  {
    return "f81dc7dae681cc15d11fa0cebf4e8f30";
  }

  static const char* value(const ::beginner_tutorials::call_map&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::call_map > {
  static const char* value()
  {
    return "beginner_tutorials/call_map";
  }

  static const char* value(const ::beginner_tutorials::call_map&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::call_mapRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::call_map >
template<>
struct MD5Sum< ::beginner_tutorials::call_mapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::call_map >::value();
  }
  static const char* value(const ::beginner_tutorials::call_mapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::call_mapRequest> should match
// service_traits::DataType< ::beginner_tutorials::call_map >
template<>
struct DataType< ::beginner_tutorials::call_mapRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::call_map >::value();
  }
  static const char* value(const ::beginner_tutorials::call_mapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::call_mapResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::call_map >
template<>
struct MD5Sum< ::beginner_tutorials::call_mapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::call_map >::value();
  }
  static const char* value(const ::beginner_tutorials::call_mapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::call_mapResponse> should match
// service_traits::DataType< ::beginner_tutorials::call_map >
template<>
struct DataType< ::beginner_tutorials::call_mapResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::call_map >::value();
  }
  static const char* value(const ::beginner_tutorials::call_mapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_CALL_MAP_H
