// Generated by gencpp from file beginner_tutorials/counterGoal.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_COUNTERGOAL_H
#define BEGINNER_TUTORIALS_MESSAGE_COUNTERGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct counterGoal_
{
  typedef counterGoal_<ContainerAllocator> Type;

  counterGoal_()
    : num_counts(0)  {
    }
  counterGoal_(const ContainerAllocator& _alloc)
    : num_counts(0)  {
  (void)_alloc;
    }



   typedef int32_t _num_counts_type;
  _num_counts_type num_counts;





  typedef boost::shared_ptr< ::beginner_tutorials::counterGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::counterGoal_<ContainerAllocator> const> ConstPtr;

}; // struct counterGoal_

typedef ::beginner_tutorials::counterGoal_<std::allocator<void> > counterGoal;

typedef boost::shared_ptr< ::beginner_tutorials::counterGoal > counterGoalPtr;
typedef boost::shared_ptr< ::beginner_tutorials::counterGoal const> counterGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::counterGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::counterGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::counterGoal_<ContainerAllocator1> & lhs, const ::beginner_tutorials::counterGoal_<ContainerAllocator2> & rhs)
{
  return lhs.num_counts == rhs.num_counts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::counterGoal_<ContainerAllocator1> & lhs, const ::beginner_tutorials::counterGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::counterGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::counterGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::counterGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::counterGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::counterGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::counterGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::counterGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68e6163c06e1ec24e81524aa0727d5c4";
  }

  static const char* value(const ::beginner_tutorials::counterGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68e6163c06e1ec24ULL;
  static const uint64_t static_value2 = 0xe81524aa0727d5c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::counterGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/counterGoal";
  }

  static const char* value(const ::beginner_tutorials::counterGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::counterGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"int32 num_counts\n"
;
  }

  static const char* value(const ::beginner_tutorials::counterGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::counterGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_counts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct counterGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::counterGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::counterGoal_<ContainerAllocator>& v)
  {
    s << indent << "num_counts: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_counts);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_COUNTERGOAL_H
