// Generated by gencpp from file beginner_tutorials/gazebo_serverResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_GAZEBO_SERVERRESPONSE_H
#define BEGINNER_TUTORIALS_MESSAGE_GAZEBO_SERVERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct gazebo_serverResponse_
{
  typedef gazebo_serverResponse_<ContainerAllocator> Type;

  gazebo_serverResponse_()
    : distance(0.0)  {
    }
  gazebo_serverResponse_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator> const> ConstPtr;

}; // struct gazebo_serverResponse_

typedef ::beginner_tutorials::gazebo_serverResponse_<std::allocator<void> > gazebo_serverResponse;

typedef boost::shared_ptr< ::beginner_tutorials::gazebo_serverResponse > gazebo_serverResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorials::gazebo_serverResponse const> gazebo_serverResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e77fb10f0c8b4833ec273aa9ac74459";
  }

  static const char* value(const ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e77fb10f0c8b483ULL;
  static const uint64_t static_value2 = 0x3ec273aa9ac74459ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/gazebo_serverResponse";
  }

  static const char* value(const ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 distance\n"
;
  }

  static const char* value(const ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gazebo_serverResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::gazebo_serverResponse_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_GAZEBO_SERVERRESPONSE_H
