// Generated by gencpp from file beginner_tutorials/gazebo_serverRequest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_GAZEBO_SERVERREQUEST_H
#define BEGINNER_TUTORIALS_MESSAGE_GAZEBO_SERVERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct gazebo_serverRequest_
{
  typedef gazebo_serverRequest_<ContainerAllocator> Type;

  gazebo_serverRequest_()
    : direction(0)  {
    }
  gazebo_serverRequest_(const ContainerAllocator& _alloc)
    : direction(0)  {
  (void)_alloc;
    }



   typedef int64_t _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator> const> ConstPtr;

}; // struct gazebo_serverRequest_

typedef ::beginner_tutorials::gazebo_serverRequest_<std::allocator<void> > gazebo_serverRequest;

typedef boost::shared_ptr< ::beginner_tutorials::gazebo_serverRequest > gazebo_serverRequestPtr;
typedef boost::shared_ptr< ::beginner_tutorials::gazebo_serverRequest const> gazebo_serverRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acc888e5f8dfeabbbf64aca41aafb072";
  }

  static const char* value(const ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacc888e5f8dfeabbULL;
  static const uint64_t static_value2 = 0xbf64aca41aafb072ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/gazebo_serverRequest";
  }

  static const char* value(const ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 direction\n"
;
  }

  static const char* value(const ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gazebo_serverRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::gazebo_serverRequest_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<int64_t>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_GAZEBO_SERVERREQUEST_H
