// Generated by gencpp from file beginner_tutorials/get_pose.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_GET_POSE_H
#define BEGINNER_TUTORIALS_MESSAGE_GET_POSE_H

#include <ros/service_traits.h>


#include <beginner_tutorials/get_poseRequest.h>
#include <beginner_tutorials/get_poseResponse.h>


namespace beginner_tutorials
{

struct get_pose
{

typedef get_poseRequest Request;
typedef get_poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_pose
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::get_pose > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::beginner_tutorials::get_pose&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::get_pose > {
  static const char* value()
  {
    return "beginner_tutorials/get_pose";
  }

  static const char* value(const ::beginner_tutorials::get_pose&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::get_poseRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::get_pose >
template<>
struct MD5Sum< ::beginner_tutorials::get_poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::get_pose >::value();
  }
  static const char* value(const ::beginner_tutorials::get_poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::get_poseRequest> should match
// service_traits::DataType< ::beginner_tutorials::get_pose >
template<>
struct DataType< ::beginner_tutorials::get_poseRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::get_pose >::value();
  }
  static const char* value(const ::beginner_tutorials::get_poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::get_poseResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::get_pose >
template<>
struct MD5Sum< ::beginner_tutorials::get_poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::get_pose >::value();
  }
  static const char* value(const ::beginner_tutorials::get_poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::get_poseResponse> should match
// service_traits::DataType< ::beginner_tutorials::get_pose >
template<>
struct DataType< ::beginner_tutorials::get_poseResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::get_pose >::value();
  }
  static const char* value(const ::beginner_tutorials::get_poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_GET_POSE_H
