// Generated by gencpp from file beginner_tutorials/JangoFett.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_JANGOFETT_H
#define BEGINNER_TUTORIALS_MESSAGE_JANGOFETT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct JangoFett_
{
  typedef JangoFett_<ContainerAllocator> Type;

  JangoFett_()
    : side(0)
    , shape()  {
    }
  JangoFett_(const ContainerAllocator& _alloc)
    : side(0)
    , shape(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _side_type;
  _side_type side;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _shape_type;
  _shape_type shape;





  typedef boost::shared_ptr< ::beginner_tutorials::JangoFett_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::JangoFett_<ContainerAllocator> const> ConstPtr;

}; // struct JangoFett_

typedef ::beginner_tutorials::JangoFett_<std::allocator<void> > JangoFett;

typedef boost::shared_ptr< ::beginner_tutorials::JangoFett > JangoFettPtr;
typedef boost::shared_ptr< ::beginner_tutorials::JangoFett const> JangoFettConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::JangoFett_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::JangoFett_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::JangoFett_<ContainerAllocator1> & lhs, const ::beginner_tutorials::JangoFett_<ContainerAllocator2> & rhs)
{
  return lhs.side == rhs.side &&
    lhs.shape == rhs.shape;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::JangoFett_<ContainerAllocator1> & lhs, const ::beginner_tutorials::JangoFett_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::JangoFett_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::JangoFett_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::JangoFett_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::JangoFett_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::JangoFett_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::JangoFett_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::JangoFett_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bce1314c2e7b82b7bed59a940875e4a6";
  }

  static const char* value(const ::beginner_tutorials::JangoFett_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbce1314c2e7b82b7ULL;
  static const uint64_t static_value2 = 0xbed59a940875e4a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::JangoFett_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/JangoFett";
  }

  static const char* value(const ::beginner_tutorials::JangoFett_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::JangoFett_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 side\n"
"string shape\n"
;
  }

  static const char* value(const ::beginner_tutorials::JangoFett_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::JangoFett_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.side);
      stream.next(m.shape);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JangoFett_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::JangoFett_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::JangoFett_<ContainerAllocator>& v)
  {
    s << indent << "side: ";
    Printer<int32_t>::stream(s, indent + "  ", v.side);
    s << indent << "shape: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.shape);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_JANGOFETT_H
