// Generated by gencpp from file beginner_tutorials/my_actResult.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_MY_ACTRESULT_H
#define BEGINNER_TUTORIALS_MESSAGE_MY_ACTRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct my_actResult_
{
  typedef my_actResult_<ContainerAllocator> Type;

  my_actResult_()
    : result(0.0)  {
    }
  my_actResult_(const ContainerAllocator& _alloc)
    : result(0.0)  {
  (void)_alloc;
    }



   typedef float _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::beginner_tutorials::my_actResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::my_actResult_<ContainerAllocator> const> ConstPtr;

}; // struct my_actResult_

typedef ::beginner_tutorials::my_actResult_<std::allocator<void> > my_actResult;

typedef boost::shared_ptr< ::beginner_tutorials::my_actResult > my_actResultPtr;
typedef boost::shared_ptr< ::beginner_tutorials::my_actResult const> my_actResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::my_actResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::my_actResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::my_actResult_<ContainerAllocator1> & lhs, const ::beginner_tutorials::my_actResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::my_actResult_<ContainerAllocator1> & lhs, const ::beginner_tutorials::my_actResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::my_actResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::my_actResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::my_actResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::my_actResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::my_actResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::my_actResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::my_actResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db954e5de3aba73b237d07575e5cac28";
  }

  static const char* value(const ::beginner_tutorials::my_actResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb954e5de3aba73bULL;
  static const uint64_t static_value2 = 0x237d07575e5cac28ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::my_actResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/my_actResult";
  }

  static const char* value(const ::beginner_tutorials::my_actResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::my_actResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"float32 result\n"
;
  }

  static const char* value(const ::beginner_tutorials::my_actResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::my_actResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_actResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::my_actResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::my_actResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<float>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_MY_ACTRESULT_H
