// Generated by gencpp from file beginner_tutorials/my_actGoal.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_MY_ACTGOAL_H
#define BEGINNER_TUTORIALS_MESSAGE_MY_ACTGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct my_actGoal_
{
  typedef my_actGoal_<ContainerAllocator> Type;

  my_actGoal_()
    : threshold(0.0)  {
    }
  my_actGoal_(const ContainerAllocator& _alloc)
    : threshold(0.0)  {
  (void)_alloc;
    }



   typedef float _threshold_type;
  _threshold_type threshold;





  typedef boost::shared_ptr< ::beginner_tutorials::my_actGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::my_actGoal_<ContainerAllocator> const> ConstPtr;

}; // struct my_actGoal_

typedef ::beginner_tutorials::my_actGoal_<std::allocator<void> > my_actGoal;

typedef boost::shared_ptr< ::beginner_tutorials::my_actGoal > my_actGoalPtr;
typedef boost::shared_ptr< ::beginner_tutorials::my_actGoal const> my_actGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::my_actGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::my_actGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::my_actGoal_<ContainerAllocator1> & lhs, const ::beginner_tutorials::my_actGoal_<ContainerAllocator2> & rhs)
{
  return lhs.threshold == rhs.threshold;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::my_actGoal_<ContainerAllocator1> & lhs, const ::beginner_tutorials::my_actGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::my_actGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::my_actGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::my_actGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::my_actGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::my_actGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::my_actGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::my_actGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "762b8eff81569601a12f7a5cd61b8c26";
  }

  static const char* value(const ::beginner_tutorials::my_actGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x762b8eff81569601ULL;
  static const uint64_t static_value2 = 0xa12f7a5cd61b8c26ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::my_actGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/my_actGoal";
  }

  static const char* value(const ::beginner_tutorials::my_actGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::my_actGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"float32 threshold \n"
;
  }

  static const char* value(const ::beginner_tutorials::my_actGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::my_actGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.threshold);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_actGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::my_actGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::my_actGoal_<ContainerAllocator>& v)
  {
    s << indent << "threshold: ";
    Printer<float>::stream(s, indent + "  ", v.threshold);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_MY_ACTGOAL_H
