// Generated by gencpp from file beginner_tutorials/my_actFeedback.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_MY_ACTFEEDBACK_H
#define BEGINNER_TUTORIALS_MESSAGE_MY_ACTFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct my_actFeedback_
{
  typedef my_actFeedback_<ContainerAllocator> Type;

  my_actFeedback_()
    : feed(0.0)  {
    }
  my_actFeedback_(const ContainerAllocator& _alloc)
    : feed(0.0)  {
  (void)_alloc;
    }



   typedef float _feed_type;
  _feed_type feed;





  typedef boost::shared_ptr< ::beginner_tutorials::my_actFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::my_actFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct my_actFeedback_

typedef ::beginner_tutorials::my_actFeedback_<std::allocator<void> > my_actFeedback;

typedef boost::shared_ptr< ::beginner_tutorials::my_actFeedback > my_actFeedbackPtr;
typedef boost::shared_ptr< ::beginner_tutorials::my_actFeedback const> my_actFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::my_actFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::my_actFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::my_actFeedback_<ContainerAllocator1> & lhs, const ::beginner_tutorials::my_actFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.feed == rhs.feed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::my_actFeedback_<ContainerAllocator1> & lhs, const ::beginner_tutorials::my_actFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::my_actFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::my_actFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::my_actFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::my_actFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::my_actFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::my_actFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::my_actFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dea712110560d1c5514ea68393636cf9";
  }

  static const char* value(const ::beginner_tutorials::my_actFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdea712110560d1c5ULL;
  static const uint64_t static_value2 = 0x514ea68393636cf9ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::my_actFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/my_actFeedback";
  }

  static const char* value(const ::beginner_tutorials::my_actFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::my_actFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"float32 feed\n"
;
  }

  static const char* value(const ::beginner_tutorials::my_actFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::my_actFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_actFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::my_actFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::my_actFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feed: ";
    Printer<float>::stream(s, indent + "  ", v.feed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_MY_ACTFEEDBACK_H
