// Auto-generated. Do not edit!

// (in-package beginner_tutorials.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class my_actFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.feed = null;
    }
    else {
      if (initObj.hasOwnProperty('feed')) {
        this.feed = initObj.feed
      }
      else {
        this.feed = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type my_actFeedback
    // Serialize message field [feed]
    bufferOffset = _serializer.float32(obj.feed, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type my_actFeedback
    let len;
    let data = new my_actFeedback(null);
    // Deserialize message field [feed]
    data.feed = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'beginner_tutorials/my_actFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'dea712110560d1c5514ea68393636cf9';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback
    float32 feed
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new my_actFeedback(null);
    if (msg.feed !== undefined) {
      resolved.feed = msg.feed;
    }
    else {
      resolved.feed = 0.0
    }

    return resolved;
    }
};

module.exports = my_actFeedback;
