// Generated by gencpp from file custom_service_assignment/custom_server.msg
// DO NOT EDIT!


#ifndef CUSTOM_SERVICE_ASSIGNMENT_MESSAGE_CUSTOM_SERVER_H
#define CUSTOM_SERVICE_ASSIGNMENT_MESSAGE_CUSTOM_SERVER_H

#include <ros/service_traits.h>


#include <custom_service_assignment/custom_serverRequest.h>
#include <custom_service_assignment/custom_serverResponse.h>


namespace custom_service_assignment
{

struct custom_server
{

typedef custom_serverRequest Request;
typedef custom_serverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct custom_server
} // namespace custom_service_assignment


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_service_assignment::custom_server > {
  static const char* value()
  {
    return "8170c3b501e907fd4247d1f4d86f297a";
  }

  static const char* value(const ::custom_service_assignment::custom_server&) { return value(); }
};

template<>
struct DataType< ::custom_service_assignment::custom_server > {
  static const char* value()
  {
    return "custom_service_assignment/custom_server";
  }

  static const char* value(const ::custom_service_assignment::custom_server&) { return value(); }
};


// service_traits::MD5Sum< ::custom_service_assignment::custom_serverRequest> should match
// service_traits::MD5Sum< ::custom_service_assignment::custom_server >
template<>
struct MD5Sum< ::custom_service_assignment::custom_serverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_service_assignment::custom_server >::value();
  }
  static const char* value(const ::custom_service_assignment::custom_serverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_service_assignment::custom_serverRequest> should match
// service_traits::DataType< ::custom_service_assignment::custom_server >
template<>
struct DataType< ::custom_service_assignment::custom_serverRequest>
{
  static const char* value()
  {
    return DataType< ::custom_service_assignment::custom_server >::value();
  }
  static const char* value(const ::custom_service_assignment::custom_serverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_service_assignment::custom_serverResponse> should match
// service_traits::MD5Sum< ::custom_service_assignment::custom_server >
template<>
struct MD5Sum< ::custom_service_assignment::custom_serverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_service_assignment::custom_server >::value();
  }
  static const char* value(const ::custom_service_assignment::custom_serverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_service_assignment::custom_serverResponse> should match
// service_traits::DataType< ::custom_service_assignment::custom_server >
template<>
struct DataType< ::custom_service_assignment::custom_serverResponse>
{
  static const char* value()
  {
    return DataType< ::custom_service_assignment::custom_server >::value();
  }
  static const char* value(const ::custom_service_assignment::custom_serverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_SERVICE_ASSIGNMENT_MESSAGE_CUSTOM_SERVER_H
