// Generated by gencpp from file custom_service_assignment/custom_serverResponse.msg
// DO NOT EDIT!


#ifndef CUSTOM_SERVICE_ASSIGNMENT_MESSAGE_CUSTOM_SERVERRESPONSE_H
#define CUSTOM_SERVICE_ASSIGNMENT_MESSAGE_CUSTOM_SERVERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_service_assignment
{
template <class ContainerAllocator>
struct custom_serverResponse_
{
  typedef custom_serverResponse_<ContainerAllocator> Type;

  custom_serverResponse_()
    : success(false)
    , message()  {
    }
  custom_serverResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::custom_service_assignment::custom_serverResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_service_assignment::custom_serverResponse_<ContainerAllocator> const> ConstPtr;

}; // struct custom_serverResponse_

typedef ::custom_service_assignment::custom_serverResponse_<std::allocator<void> > custom_serverResponse;

typedef boost::shared_ptr< ::custom_service_assignment::custom_serverResponse > custom_serverResponsePtr;
typedef boost::shared_ptr< ::custom_service_assignment::custom_serverResponse const> custom_serverResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_service_assignment::custom_serverResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_service_assignment::custom_serverResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_service_assignment::custom_serverResponse_<ContainerAllocator1> & lhs, const ::custom_service_assignment::custom_serverResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_service_assignment::custom_serverResponse_<ContainerAllocator1> & lhs, const ::custom_service_assignment::custom_serverResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_service_assignment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_service_assignment::custom_serverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_service_assignment::custom_serverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_service_assignment::custom_serverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_service_assignment::custom_serverResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_service_assignment::custom_serverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_service_assignment::custom_serverResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_service_assignment::custom_serverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::custom_service_assignment::custom_serverResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_service_assignment::custom_serverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_service_assignment/custom_serverResponse";
  }

  static const char* value(const ::custom_service_assignment::custom_serverResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_service_assignment::custom_serverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
;
  }

  static const char* value(const ::custom_service_assignment::custom_serverResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_service_assignment::custom_serverResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct custom_serverResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_service_assignment::custom_serverResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_service_assignment::custom_serverResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_SERVICE_ASSIGNMENT_MESSAGE_CUSTOM_SERVERRESPONSE_H
