(cl:defpackage beginner_tutorials-msg
  (:use )
  (:export
   "<JANGOFETT>"
   "JANGOFETT"
   "<MY_ACTACTION>"
   "MY_ACTACTION"
   "<MY_ACTACTIONFEEDBACK>"
   "MY_ACTACTIONFEEDBACK"
   "<MY_ACTACTIONGOAL>"
   "MY_ACTACTIONGOAL"
   "<MY_ACTACTIONRESULT>"
   "MY_ACTACTIONRESULT"
   "<MY_ACTFEEDBACK>"
   "MY_ACTFEEDBACK"
   "<MY_ACTGOAL>"
   "MY_ACTGOAL"
   "<MY_ACTRESULT>"
   "MY_ACTRESULT"
  ))

