; Auto-generated. Do not edit!


(cl:in-package beginner_tutorials-msg)


;//! \htmlinclude my_actGoal.msg.html

(cl:defclass <my_actGoal> (roslisp-msg-protocol:ros-message)
  ((threshold
    :reader threshold
    :initarg :threshold
    :type cl:float
    :initform 0.0))
)

(cl:defclass my_actGoal (<my_actGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <my_actGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'my_actGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name beginner_tutorials-msg:<my_actGoal> is deprecated: use beginner_tutorials-msg:my_actGoal instead.")))

(cl:ensure-generic-function 'threshold-val :lambda-list '(m))
(cl:defmethod threshold-val ((m <my_actGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader beginner_tutorials-msg:threshold-val is deprecated.  Use beginner_tutorials-msg:threshold instead.")
  (threshold m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <my_actGoal>) ostream)
  "Serializes a message object of type '<my_actGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'threshold))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <my_actGoal>) istream)
  "Deserializes a message object of type '<my_actGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'threshold) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<my_actGoal>)))
  "Returns string type for a message object of type '<my_actGoal>"
  "beginner_tutorials/my_actGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'my_actGoal)))
  "Returns string type for a message object of type 'my_actGoal"
  "beginner_tutorials/my_actGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<my_actGoal>)))
  "Returns md5sum for a message object of type '<my_actGoal>"
  "762b8eff81569601a12f7a5cd61b8c26")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'my_actGoal)))
  "Returns md5sum for a message object of type 'my_actGoal"
  "762b8eff81569601a12f7a5cd61b8c26")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<my_actGoal>)))
  "Returns full string definition for message of type '<my_actGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%float32 threshold ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'my_actGoal)))
  "Returns full string definition for message of type 'my_actGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%float32 threshold ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <my_actGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <my_actGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'my_actGoal
    (cl:cons ':threshold (threshold msg))
))
